import "./math.ts";
import "./text.ts";
import "./colour.ts";
import "./controls.ts";
import "./json.ts";
import "./logic.ts";
import "./advanced.ts";
import "./function.ts";
import "./browser.ts";
import "./blocks.ts";
import "./category.ts"
